CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL COMMENT '상품명. 주문 시 이 값을 order_item에 복사한다',
    price BIGINT NOT NULL COMMENT '단가. 결제 금액은 클라이언트 값이 아니라 이 값으로 재계산한다',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
COMMENT ON TABLE product IS '판매 상품';

CREATE TABLE company (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(100) NOT NULL COMMENT '회사명',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
COMMENT ON TABLE company IS '결제 주체가 되는 회사';

CREATE TABLE "order" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_key VARCHAR(100) NOT NULL COMMENT '클라이언트가 발급하는 주문 식별자. 장바구니가 바뀔 때만 새로 발급해 재시도가 같은 주문으로 이어지게 한다',
    company_seq BIGINT NOT NULL COMMENT 'company.id',
    total_price BIGINT NOT NULL COMMENT '주문 합계. 재시도 시 이 값이 다르면 거부한다',
    delivery_date DATE NOT NULL COMMENT '배송 보장일. 예정이 아니라 보장이라 결제 시점에 재검증한다',
    status SMALLINT NOT NULL COMMENT 'OrderStatus 코드. 결제 실패는 시도의 결과일 뿐이라 주문은 결제될 때까지 PENDING_PAYMENT로 둔다',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ,CONSTRAINT uk_order_order_key UNIQUE (order_key)
);
COMMENT ON TABLE "order" IS '주문. 한 주문에 여러 결제 시도가 붙을 수 있다';

CREATE TABLE order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_seq BIGINT NOT NULL COMMENT 'order.id',
    item_name VARCHAR(255) NOT NULL COMMENT '주문 시점의 상품명 사본. 상품이 바뀌어도 주문 내용은 고정된다',
    unit_price BIGINT NOT NULL COMMENT '주문 시점의 단가 사본',
    quantity INTEGER NOT NULL COMMENT '수량',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
COMMENT ON TABLE order_item IS '주문 항목. 합계가 같아도 구성이 다를 수 있어 재시도 시 이 내용까지 대조한다';

CREATE TABLE payment_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_key VARCHAR(100) NOT NULL COMMENT '결제 시도 식별자. 시도마다 새로 발급한다',
    order_seq BIGINT NOT NULL COMMENT 'order.id',
    moid VARCHAR(100) NOT NULL COMMENT 'PG에 넘기는 주문번호(= PG의 orderId). 대사가 양쪽을 잇는 키다',
    tid VARCHAR(100) COMMENT 'PG의 결제 키. 승인 응답에만 들어 있어 취소하려면 이 값이 필요하다',
    amount BIGINT NOT NULL COMMENT '승인 요청 금액',
    status SMALLINT NOT NULL COMMENT 'PaymentTransactionStatus 코드',
    approved_at TIMESTAMP COMMENT 'PG가 알려준 승인 시각. 대사가 우리 목록과 PG 목록을 같은 축으로 자르는 기준',
    fail_code SMALLINT COMMENT '실패 사유. PaymentFailCode 코드. 승인 실패, 재처리의 종결 사유, 대사의 취소 결과가 여기 남는다',
    fail_message VARCHAR(500) COMMENT '실패 사유 메시지. PG가 준 코드와 메시지는 여기에 원문으로 남는다',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시각. 첫 확인 대기와 확정 기한이 모두 이 값에서 계산된다',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uk_payment_transaction_payment_key UNIQUE (payment_key)
);
COMMENT ON TABLE payment_transaction IS '결제 시도. 승인 호출보다 먼저 커밋되므로 PG에 있는 거래는 반드시 여기에도 있다';

CREATE TABLE company_billing_key (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_seq BIGINT NOT NULL COMMENT 'company.id',
    payment_system SMALLINT NOT NULL COMMENT 'PaymentSystem 코드',
    customer_key VARCHAR(300) NOT NULL COMMENT '빌링키 발급에 쓴 고객 식별자',
    billing_key VARCHAR(200) NOT NULL COMMENT 'PG가 발급한 자동결제 키. 인증은 이 키를 받는 시점에 이미 끝나 있다',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uk_company_billing_key UNIQUE (company_seq, payment_system)
);
COMMENT ON TABLE company_billing_key IS '회사별 자동결제 빌링키';

CREATE TABLE reconciliation_discrepancy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_system SMALLINT NOT NULL COMMENT 'PaymentSystem 코드',
    type SMALLINT NOT NULL COMMENT '불일치 유형. DiscrepancyType 코드',
    status SMALLINT NOT NULL COMMENT '처리 상태. DiscrepancyStatus 코드. 대사는 OPEN(1)으로 넣기만 하고, 종결은 관리자가 RESOLVED(2)로 바꾼다',
    moid VARCHAR(100) NOT NULL COMMENT '양쪽을 잇는 키(= PG의 orderId). 한쪽에만 있으면 있는 쪽 값',
    our_status SMALLINT COMMENT '감지 시점 우리 상태. PaymentTransactionStatus 코드. 우리 기록이 없으면 NULL',
    pg_status SMALLINT COMMENT '감지 시점 PG 판정. PgPaymentStatus 코드. PG에 없으면 NULL',
    our_amount BIGINT COMMENT '감지 시점 우리 금액',
    pg_amount BIGINT COMMENT '감지 시점 PG 금액',
    detail VARCHAR(500) COMMENT '다른 곳에 저장되지 않는 맥락. 취소 실패 사유, PG 상태 원문 등',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '감지 시각',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '마지막 변경(종결) 시각'
);
COMMENT ON TABLE reconciliation_discrepancy IS '일일 대사가 발견한 불일치. 행은 감지 시점의 박제라 이후 갱신하지 않는다';
